### PR TITLE
Update pictures

### PR DESCRIPTION
**Pull request by am-cornelis**
Add pictures that are more up-to-date

I wondered whether to delete the pictures that weren't used anymore (`/img/2014`) to keep the repo tidy. For now decided to leave them in (the same way we have the artifacts from previous years on the wiki) but happy to actually move them with the other artifacts...

### CODE REVIEW

**Review by robertfirek — APPROVED** [review]

**Comment by jukecraft** [comment]
Those captions are great!

**Comment by jukecraft** [comment]
Screenshot 2019-03-28 at 14 01 51
@am-cornelis is this how you imagined it to look?

**Comment by am-cornelis** [comment]
Yep, though now that I look at it again, I think the outdoor one could be cropped to be the same height as the other 2, or less even. Anything else we can improve?

**Comment by jukecraft** [comment]
I was just wondering if we could have your titles displayed, I can't see them and they're good :)

**Pull request merged**
