### PR TITLE
Add images from 2019

### PR DESCRIPTION
**Pull request by tomphp**

### CODE REVIEW

**Comment by jukecraft** [comment]
Awesome pictures! Can we put matthew3.jpg as the first one? I think it gives a really good impression of what we do

**Comment by tomphp** [comment]
@jukecraft done 👍

**Comment by jukecraft** [comment]
did you? :D

**Comment by tomphp** [comment]
I did @jukecraft, it's on the branch but not showing up in the PR - possibly a result of this https://www.githubstatus.com/ ?

Of course it's also possible that I've done something stupid 😁

**Comment by jukecraft** [comment]
Ah yeah! makes sense. Let's wait a bit

**Review by jukecraft — APPROVED** [review]

**Comment by jukecraft** [comment]
that commit didn't take, can you please make another PR?

**Pull request merged**
